import type { Recipe } from "./types";

/** Base recipe amounts use grams for produce & protein so scaling maps to a kitchen scale. */
export const MOCK_RECIPES: Recipe[] = [
  {
    id: "recipe-sous-vide-salmon",
    name: "Sous Vide Salmon with Asparagus",
    baseCalories: 520,
    baseProtein: 42,
    baseCarbs: 18,
    baseFats: 28,
    baseIngredients: [
      { name: "Salmon Fillet", amount: 180, unit: "g", macroType: "protein" },
      { name: "Asparagus", amount: 200, unit: "g", macroType: "carb" },
      { name: "Olive Oil", amount: 14, unit: "g", macroType: "fat" },
      { name: "Lemon", amount: 30, unit: "g", macroType: "carb" },
      { name: "Garlic", amount: 10, unit: "g", macroType: "pantry" },
      { name: "Dill", amount: 5, unit: "g", macroType: "pantry" },
      { name: "Salt", amount: 1, unit: "pinch", macroType: "pantry" },
    ],
    instructions: [
      "Season salmon with salt, garlic, and dill.",
      "Vacuum-seal or use zip bag; sous vide at 125°F (52°C) for 45 min.",
      "Blanch asparagus 2 min; toss with olive oil and lemon zest.",
      "Sear salmon 30 sec per side in hot pan for color.",
      "Plate asparagus, top with salmon, squeeze lemon.",
    ],
  },
  {
    id: "recipe-air-fry-chicken",
    name: "Air-Fried Chicken & Broccoli",
    baseCalories: 480,
    baseProtein: 48,
    baseCarbs: 22,
    baseFats: 18,
    baseIngredients: [
      { name: "Chicken Breast", amount: 200, unit: "g", macroType: "protein" },
      { name: "Broccoli Florets", amount: 250, unit: "g", macroType: "carb" },
      { name: "Olive Oil Spray", amount: 1, unit: "spray", macroType: "fat" },
      { name: "Smoked Paprika", amount: 1, unit: "tsp", macroType: "pantry" },
      { name: "Garlic Powder", amount: 0.5, unit: "tsp", macroType: "pantry" },
      { name: "Greek Yogurt", amount: 30, unit: "g", macroType: "fat" },
    ],
    instructions: [
      "Cube chicken; coat with paprika, garlic powder, and spray oil.",
      "Air fry chicken at 380°F for 12 min, shake halfway.",
      "Toss broccoli with spray; air fry 8 min until crisp-tender.",
      "Mix yogurt with pinch of paprika for drizzle.",
      "Combine and serve immediately.",
    ],
  },
  {
    id: "recipe-lean-beef-stir-fry",
    name: "Lean Beef Stir Fry",
    baseCalories: 550,
    baseProtein: 45,
    baseCarbs: 48,
    baseFats: 16,
    baseIngredients: [
      { name: "Lean Beef Strips", amount: 180, unit: "g", macroType: "protein" },
      { name: "Bell Pepper", amount: 150, unit: "g", macroType: "carb" },
      { name: "Brown Rice", amount: 150, unit: "g", macroType: "carb" },
      { name: "Soy Sauce", amount: 2, unit: "tbsp", macroType: "pantry" },
      { name: "Ginger", amount: 5, unit: "g", macroType: "pantry" },
      { name: "Sesame Oil", amount: 5, unit: "g", macroType: "fat" },
      { name: "Green Onion", amount: 30, unit: "g", macroType: "carb" },
    ],
    instructions: [
      "Cook brown rice per package; keep warm.",
      "Stir-fry beef over high heat 2–3 min; set aside.",
      "Sauté peppers and ginger 3 min; return beef.",
      "Add soy sauce and sesame oil; toss 1 min.",
      "Serve over rice; garnish with green onion.",
    ],
  },
  {
    id: "recipe-turkey-chili",
    name: "High-Protein Turkey Chili",
    baseCalories: 490,
    baseProtein: 44,
    baseCarbs: 42,
    baseFats: 14,
    baseIngredients: [
      { name: "Ground Turkey", amount: 200, unit: "g", macroType: "protein" },
      { name: "Black Beans", amount: 120, unit: "g", macroType: "carb" },
      { name: "Diced Tomatoes", amount: 200, unit: "g", macroType: "carb" },
      { name: "Onion", amount: 55, unit: "g", macroType: "carb" },
      { name: "Chili Powder", amount: 2, unit: "tsp", macroType: "pantry" },
      { name: "Cumin", amount: 1, unit: "tsp", macroType: "pantry" },
      { name: "Avocado", amount: 50, unit: "g", macroType: "fat" },
    ],
    instructions: [
      "Brown turkey with onion until no pink remains.",
      "Add tomatoes, beans, chili powder, and cumin.",
      "Simmer 25 min, stirring occasionally.",
      "Adjust seasoning; top with diced avocado.",
    ],
  },
  {
    id: "recipe-shrimp-zoodles",
    name: "Garlic Shrimp Zoodles",
    baseCalories: 380,
    baseProtein: 38,
    baseCarbs: 14,
    baseFats: 20,
    baseIngredients: [
      { name: "Shrimp", amount: 200, unit: "g", macroType: "protein" },
      { name: "Zucchini", amount: 400, unit: "g", macroType: "carb" },
      { name: "Cherry Tomatoes", amount: 100, unit: "g", macroType: "carb" },
      { name: "Garlic", amount: 15, unit: "g", macroType: "pantry" },
      { name: "Butter", amount: 14, unit: "g", macroType: "fat" },
      { name: "Parsley", amount: 8, unit: "g", macroType: "pantry" },
    ],
    instructions: [
      "Spiralize zucchini; pat dry.",
      "Sauté garlic in butter 30 sec; add shrimp 2 min per side.",
      "Add tomatoes; cook 2 min.",
      "Toss zoodles 2–3 min until just tender.",
      "Finish with parsley.",
    ],
  },
  {
    id: "recipe-tofu-bowl",
    name: "Crispy Tofu Power Bowl",
    baseCalories: 510,
    baseProtein: 32,
    baseCarbs: 52,
    baseFats: 18,
    baseIngredients: [
      { name: "Extra-Firm Tofu", amount: 200, unit: "g", macroType: "protein" },
      { name: "Quinoa", amount: 120, unit: "g", macroType: "carb" },
      { name: "Kale", amount: 80, unit: "g", macroType: "carb" },
      { name: "Tahini", amount: 15, unit: "g", macroType: "fat" },
      { name: "Soy Sauce", amount: 15, unit: "g", macroType: "pantry" },
      { name: "Sriracha", amount: 5, unit: "g", macroType: "pantry" },
    ],
    instructions: [
      "Press tofu; cube and bake at 400°F for 25 min.",
      "Cook quinoa; massage kale with drop of tahini.",
      "Whisk tahini, soy sauce, sriracha with water to drizzle.",
      "Assemble bowl: quinoa, kale, tofu, sauce.",
    ],
  },
  {
    id: "recipe-cod-sweet-potato",
    name: "Baked Cod with Sweet Potato",
    baseCalories: 460,
    baseProtein: 40,
    baseCarbs: 38,
    baseFats: 12,
    baseIngredients: [
      { name: "Cod Fillet", amount: 200, unit: "g", macroType: "protein" },
      { name: "Sweet Potato", amount: 200, unit: "g", macroType: "carb" },
      { name: "Green Beans", amount: 150, unit: "g", macroType: "carb" },
      { name: "Olive Oil", amount: 5, unit: "g", macroType: "fat" },
      { name: "Thyme", amount: 1, unit: "tsp", macroType: "pantry" },
      { name: "Lemon", amount: 30, unit: "g", macroType: "pantry" },
    ],
    instructions: [
      "Cube sweet potato; roast at 425°F for 20 min.",
      "Season cod with thyme, oil, lemon; bake 12 min.",
      "Steam green beans 4 min.",
      "Plate cod over sweet potato with beans.",
    ],
  },
  {
    id: "recipe-pork-tenderloin",
    name: "Herb Pork Tenderloin & Brussels",
    baseCalories: 500,
    baseProtein: 46,
    baseCarbs: 28,
    baseFats: 22,
    baseIngredients: [
      { name: "Pork Tenderloin", amount: 180, unit: "g", macroType: "protein" },
      { name: "Brussels Sprouts", amount: 200, unit: "g", macroType: "carb" },
      { name: "Apple", amount: 90, unit: "g", macroType: "carb" },
      { name: "Dijon Mustard", amount: 15, unit: "g", macroType: "pantry" },
      { name: "Rosemary", amount: 1, unit: "tsp", macroType: "pantry" },
      { name: "Balsamic Vinegar", amount: 15, unit: "g", macroType: "pantry" },
    ],
    instructions: [
      "Rub pork with mustard and rosemary.",
      "Roast pork at 400°F until 145°F internal, ~22 min.",
      "Halve sprouts; roast with apple 18 min.",
      "Deglaze pan with balsamic; slice pork.",
    ],
  },
];
